### ISSUE TITLE
Parsing of honorific prefix preceding a Person's name incomplete

### ISSUE THREAD

**Issue by mirjan-hoffmann** [virtUOS/edusharing-opencast-importer#48]
An honorific prefix preceding a Person's name such as Dr/Mrs/Mr/Prof is parsed by the importer. But it seems that this is incomplete - some parts of the prefix are used as name currently, but should be included in the prefix

examples

* `Dr. jur. Matthew LeMieux` becomes (Title: `Dr.`, Name: `jur. Matthew LeMieux`), but should be (Title: `Dr. jur.`, Name: `Matthew LeMieux`)
* `Prof. Dr. phil. Thomas Vogtherr` becomes (Title: `Prof. Dr.`, Name: `phil. Thomas Vogtherr`), but should be (Title: `Prof. Dr. phil.`, Name: `Thomas Vogtherr`)

**Comment by ffeyen** [comment]
Quick'n'dirty approach: We could just remove this German Doktor additions like `phil.`, `rer. nat.` and so on. 
Their is a list at Wikipedia.
Alternativ approach is to fix this in the used npm package https://github.com/RateGravity/parse-full-name. This would be a nice community approach as I couldn't find a lib which solves this "German academic title"-Problem.

**Comment by mirjan-hoffmann** [comment]
I'll implement the quick solution now and will use https://de.wikipedia.org/wiki/Liste_akademischer_Grade_(Deutschland) for this
